version: '3.8'

services:
  web:
    build: .
    ports:
      - "4004:4004"
    volumes:
      - ./app:/app
    environment:
      - PYTHONPATH=/app
    # Para desarrollo con auto-reload
    command: uvicorn main:app --host 0.0.0.0 --port 4004 --reload